let ALL_BRICKLINK_SOLID_COLORS = [
    // HEX-values must be lower-case.
    // Downloaded + converted from https://rebrickable.com/colors/

    { "id": 0,     "name": "Black",                        "hex": "#05131d", trans: false },
    { "id": 1,     "name": "Blue",                         "hex": "#0055bf", trans: false },
    { "id": 2,     "name": "Green",                        "hex": "#237841", trans: false },
    { "id": 3,     "name": "Dark Turquoise",               "hex": "#008f9b", trans: false },
    { "id": 4,     "name": "Red",                          "hex": "#c91a09", trans: false },
    { "id": 5,     "name": "Dark Pink",                    "hex": "#c870a0", trans: false },
    { "id": 6,     "name": "Brown",                        "hex": "#583927", trans: false },
    { "id": 7,     "name": "Light Gray",                   "hex": "#9ba19d", trans: false },
    { "id": 8,     "name": "Dark Gray",                    "hex": "#6d6e5c", trans: false },
    { "id": 9,     "name": "Light Blue",                   "hex": "#b4d2e3", trans: false },
    { "id": 10,    "name": "Bright Green",                 "hex": "#4b9f4a", trans: false },
    { "id": 11,    "name": "Light Turquoise",              "hex": "#55a5af", trans: false },
    { "id": 12,    "name": "Salmon",                       "hex": "#f2705e", trans: false },
    { "id": 13,    "name": "Pink",                         "hex": "#fc97ac", trans: false },
    { "id": 14,    "name": "Yellow",                       "hex": "#f2cd37", trans: false },
    { "id": 15,    "name": "White",                        "hex": "#ffffff", trans: false },
    { "id": 17,    "name": "Light Green",                  "hex": "#c2dab8", trans: false },
    { "id": 18,    "name": "Light Yellow",                 "hex": "#fbe696", trans: false },
    { "id": 19,    "name": "Tan",                          "hex": "#e4cd9e", trans: false },
    { "id": 20,    "name": "Light Violet",                 "hex": "#c9cae2", trans: false },
//  { "id": 21,    "name": "Glow In Dark Opaque",          "hex": "#d4d5c9", trans: false },
    { "id": 22,    "name": "Purple",                       "hex": "#81007b", trans: false },
    { "id": 23,    "name": "Dark Blue-Violet",             "hex": "#2032b0", trans: false },
    { "id": 25,    "name": "Orange",                       "hex": "#fe8a18", trans: false },
    { "id": 26,    "name": "Magenta",                      "hex": "#923978", trans: false },
    { "id": 27,    "name": "Lime",                         "hex": "#bbe90b", trans: false },
    { "id": 28,    "name": "Dark Tan",                     "hex": "#958a73", trans: false },
    { "id": 29,    "name": "Bright Pink",                  "hex": "#e4adc8", trans: false },
    { "id": 30,    "name": "Medium Lavender",              "hex": "#ac78ba", trans: false },
    { "id": 31,    "name": "Lavender",                     "hex": "#e1d5ed", trans: false },
//  { "id": 32,    "name": "Trans-Black IR Lens",          "hex": "#635f52", trans: true  },
//  { "id": 33,    "name": "Trans-Dark Blue",              "hex": "#0020a0", trans: true  },
//  { "id": 34,    "name": "Trans-Green",                  "hex": "#84b68d", trans: true  },
//  { "id": 35,    "name": "Trans-Bright Green",           "hex": "#d9e4a7", trans: true  },
//  { "id": 36,    "name": "Trans-Red",                    "hex": "#c91a09", trans: true  },
//  { "id": 40,    "name": "Trans-Brown",                  "hex": "#635f52", trans: true  },
//  { "id": 41,    "name": "Trans-Light Blue",             "hex": "#aeefec", trans: true  },
//  { "id": 42,    "name": "Trans-Neon Green",             "hex": "#f8f184", trans: true  },
//  { "id": 43,    "name": "Trans-Very Lt Blue",           "hex": "#c1dff0", trans: true  },
//  { "id": 45,    "name": "Trans-Dark Pink",              "hex": "#df6695", trans: true  },
//  { "id": 46,    "name": "Trans-Yellow",                 "hex": "#f5cd2f", trans: true  },
//  { "id": 47,    "name": "Trans-Clear",                  "hex": "#fcfcfc", trans: true  },
//  { "id": 52,    "name": "Trans-Purple",                 "hex": "#a5a5cb", trans: true  },
//  { "id": 54,    "name": "Trans-Neon Yellow",            "hex": "#dab000", trans: true  },
//  { "id": 57,    "name": "Trans-Neon Orange",            "hex": "#ff800d", trans: true  },
//  { "id": 60,    "name": "Chrome Antique Brass",         "hex": "#645a4c", trans: false },
//  { "id": 61,    "name": "Chrome Blue",                  "hex": "#6c96bf", trans: false },
//  { "id": 62,    "name": "Chrome Green",                 "hex": "#3cb371", trans: false },
//  { "id": 63,    "name": "Chrome Pink",                  "hex": "#aa4d8e", trans: false },
//  { "id": 64,    "name": "Chrome Black",                 "hex": "#1b2a34", trans: false },
    { "id": 68,    "name": "Very Light Orange",            "hex": "#f3cf9b", trans: false },
    { "id": 69,    "name": "Light Purple",                 "hex": "#cd6298", trans: false },
    { "id": 70,    "name": "Reddish Brown",                "hex": "#582a12", trans: false },
    { "id": 71,    "name": "Light Bluish Gray",            "hex": "#a0a5a9", trans: false },
    { "id": 72,    "name": "Dark Bluish Gray",             "hex": "#6c6e68", trans: false },
    { "id": 73,    "name": "Medium Blue",                  "hex": "#5a93db", trans: false },
    { "id": 74,    "name": "Medium Green",                 "hex": "#73dca1", trans: false },
//  { "id": 75,    "name": "Speckle Black-Copper",         "hex": "#05131d", trans: false },
//  { "id": 76,    "name": "Speckle DBGray-Silver",        "hex": "#6c6e68", trans: false },
    { "id": 77,    "name": "Light Pink",                   "hex": "#fecccf", trans: false },
    { "id": 78,     "name": "Light Nougat",                "hex": "#f6d7b3", trans: false },
    { "id": 79,    "name": "Milky White",                  "hex": "#ffffff", trans: false },
//  { "id": 80,    "name": "Metallic Silver",              "hex": "#a5a9b4", trans: false },
//  { "id": 81,    "name": "Metallic Green",               "hex": "#899b5f", trans: false },
//  { "id": 82,    "name": "Metallic Gold",                "hex": "#dbac34", trans: false },
    { "id": 84,    "name": "Medium Nougat",                "hex": "#aa7d55", trans: false },
    { "id": 85,    "name": "Dark Purple",                  "hex": "#3f3691", trans: false },
    { "id": 86,    "name": "Light Brown",                  "hex": "#7c503a", trans: false },
    { "id": 89,    "name": "Royal Blue",                   "hex": "#4c61db", trans: false },
    { "id": 92,    "name": "Nougat",                       "hex": "#d09168", trans: false },
    { "id": 100,   "name": "Light Salmon",                 "hex": "#febabd", trans: false },
    { "id": 110,   "name": "Violet",                       "hex": "#4354a3", trans: false },
    { "id": 112,   "name": "Medium Bluish Violet",         "hex": "#6874ca", trans: false },
//  { "id": 114,   "name": "Glitter Trans-Dark Pink",      "hex": "#df6695", trans: true  },
    { "id": 115,   "name": "Medium Lime",                  "hex": "#c7d23c", trans: false },
//  { "id": 117,   "name": "Glitter Trans-Clear",          "hex": "#ffffff", trans: true  },
    { "id": 118,   "name": "Aqua",                         "hex": "#b3d7d1", trans: false },
    { "id": 120,   "name": "Light Lime",                   "hex": "#d9e4a7", trans: false },
    { "id": 125,   "name": "Light Orange",                 "hex": "#f9ba61", trans: false },
//  { "id": 129,   "name": "Glitter Trans-Purple",         "hex": "#a5a5cb", trans: true  },
//  { "id": 132,   "name": "Speckle Black-Silver",         "hex": "#05131d", trans: false },
//  { "id": 133,   "name": "Speckle Black-Gold",           "hex": "#05131d", trans: false },
    { "id": 134,   "name": "Copper",                       "hex": "#ae7a59", trans: false },
//  { "id": 135,   "name": "Pearl Light Gray",             "hex": "#9ca3a8", trans: false },
//  { "id": 137,   "name": "Pearl Sand Blue",              "hex": "#7988a1", trans: false },
//  { "id": 142,   "name": "Pearl Light Gold",             "hex": "#dcbc81", trans: false },
//  { "id": 143,   "name": "Trans-Medium Blue",            "hex": "#cfe2f7", trans: true  },
//  { "id": 148,   "name": "Pearl Dark Gray",              "hex": "#575857", trans: false },
//  { "id": 150,   "name": "Pearl Very Light Gray",        "hex": "#abadac", trans: false },
    { "id": 151,   "name": "Very Light Bluish Gray",       "hex": "#e6e3e0", trans: false },
    { "id": 158,   "name": "Yellowish Green",              "hex": "#dfeea5", trans: false },
    { "id": 178,   "name": "Flat Dark Gold",               "hex": "#b48455", trans: false },
    { "id": 179,   "name": "Flat Silver",                  "hex": "#898788", trans: false },
//  { "id": 182,   "name": "Trans-Orange",                 "hex": "#f08f1c", trans: true  },
//  { "id": 183,   "name": "Pearl White",                  "hex": "#f2f3f2", trans: false },
    { "id": 191,   "name": "Bright Light Orange",          "hex": "#f8bb3d", trans: false },
    { "id": 212,   "name": "Bright Light Blue",            "hex": "#9fc3e9", trans: false },
    { "id": 216,   "name": "Rust",                         "hex": "#b31004", trans: false },
    { "id": 226,   "name": "Bright Light Yellow",          "hex": "#fff03a", trans: false },
//  { "id": 230,   "name": "Trans-Pink",                   "hex": "#e4adc8", trans: true  },
    { "id": 232,   "name": "Sky Blue",                     "hex": "#7dbfdd", trans: false },
//  { "id": 236,   "name": "Trans-Light Purple",           "hex": "#96709f", trans: true  },
    { "id": 272,   "name": "Dark Blue",                    "hex": "#0a3463", trans: false },
    { "id": 288,   "name": "Dark Green",                   "hex": "#184632", trans: false },
//  { "id": 294,   "name": "Glow In Dark Trans",           "hex": "#bdc6ad", trans: true  },
//  { "id": 297,   "name": "Pearl Gold",                   "hex": "#aa7f2e", trans: false },
    { "id": 308,   "name": "Dark Brown",                   "hex": "#352100", trans: false },
    { "id": 313,   "name": "Maersk Blue",                  "hex": "#3592c3", trans: false },
    { "id": 320,   "name": "Dark Red",                     "hex": "#720e0f", trans: false },
    { "id": 321,   "name": "Dark Azure",                   "hex": "#078bc9", trans: false },
    { "id": 322,   "name": "Medium Azure",                 "hex": "#36aebf", trans: false },
    { "id": 323,   "name": "Light Aqua",                   "hex": "#adc3c0", trans: false },
    { "id": 326,   "name": "Olive Green",                  "hex": "#9b9a5a", trans: false },
//  { "id": 334,   "name": "Chrome Gold",                  "hex": "#bba53d", trans: false },
    { "id": 335,   "name": "Sand Red",                     "hex": "#d67572", trans: false },
    { "id": 351,   "name": "Medium Dark Pink",             "hex": "#f785b1", trans: false },
    { "id": 366,   "name": "Earth Orange",                 "hex": "#fa9c1c", trans: false },
    { "id": 373,   "name": "Sand Purple",                  "hex": "#845e84", trans: false },
    { "id": 378,   "name": "Sand Green",                   "hex": "#a0bcac", trans: false },
    { "id": 379,   "name": "Sand Blue",                    "hex": "#6074a1", trans: false },
//  { "id": 383,   "name": "Chrome Silver",                "hex": "#e0e0e0", trans: false },
//  { "id": 450,   "name": "Fabuland Brown",               "hex": "#b67b50", trans: false },
    { "id": 462,   "name": "Medium Orange",                "hex": "#ffa70b", trans: false },
    { "id": 484,   "name": "Dark Orange",                  "hex": "#a95500", trans: false },
    { "id": 503,   "name": "Very Light Gray",              "hex": "#e6e3da", trans: false },
//  { "id": 1000,  "name": "Glow in Dark White",           "hex": "#d9d9d9", trans: false },
    { "id": 1001,  "name": "Medium Violet",                "hex": "#9391e4", trans: false },
//  { "id": 1002,  "name": "Glitter Trans-Neon Green",     "hex": "#c0f500", trans: true  },
//  { "id": 1003,  "name": "Glitter Trans-Light Blue",     "hex": "#68bcc5", trans: true  },
//  { "id": 1004,  "name": "Trans-Flame Yellowish Orange", "hex": "#fcb76d", trans: true  },
//  { "id": 1005,  "name": "Trans-Fire Yellow",            "hex": "#fbe890", trans: true  },
//  { "id": 1006,  "name": "Trans-Light Royal Blue",       "hex": "#b4d4f7", trans: true  },
    { "id": 1007,  "name": "Reddish Lilac",                "hex": "#8e5597", trans: false },
//  { "id": 1008,  "name": "Vintage Blue",                 "hex": "#039cbd", trans: false },
//  { "id": 1009,  "name": "Vintage Green",                "hex": "#1e601e", trans: false },
//  { "id": 1010,  "name": "Vintage Red",                  "hex": "#ca1f08", trans: false },
//  { "id": 1011,  "name": "Vintage Yellow",               "hex": "#f3c305", trans: false },
//  { "id": 1012,  "name": "Fabuland Orange",              "hex": "#ef9121", trans: false },
//  { "id": 1013,  "name": "Modulex White",                "hex": "#f4f4f4", trans: false },
//  { "id": 1014,  "name": "Modulex Light Bluish Gray",    "hex": "#afb5c7", trans: false },
//  { "id": 1015,  "name": "Modulex Light Gray",           "hex": "#9c9c9c", trans: false },
//  { "id": 1016,  "name": "Modulex Charcoal Gray",        "hex": "#595d60", trans: false },
//  { "id": 1017,  "name": "Modulex Tile Gray",            "hex": "#6b5a5a", trans: false },
//  { "id": 1018,  "name": "Modulex Black",                "hex": "#4d4c52", trans: false },
//  { "id": 1019,  "name": "Modulex Tile Brown",           "hex": "#330000", trans: false },
//  { "id": 1020,  "name": "Modulex Terracotta",           "hex": "#5c5030", trans: false },
//  { "id": 1021,  "name": "Modulex Brown",                "hex": "#907450", trans: false },
//  { "id": 1022,  "name": "Modulex Buff",                 "hex": "#dec69c", trans: false },
//  { "id": 1023,  "name": "Modulex Red",                  "hex": "#b52c20", trans: false },
//  { "id": 1024,  "name": "Modulex Pink Red",             "hex": "#f45c40", trans: false },
//  { "id": 1025,  "name": "Modulex Orange",               "hex": "#f47b30", trans: false },
//  { "id": 1026,  "name": "Modulex Light Orange",         "hex": "#f7ad63", trans: false },
//  { "id": 1027,  "name": "Modulex Light Yellow",         "hex": "#ffe371", trans: false },
//  { "id": 1028,  "name": "Modulex Ochre Yellow",         "hex": "#fed557", trans: false },
//  { "id": 1029,  "name": "Modulex Lemon",                "hex": "#bdc618", trans: false },
//  { "id": 1030,  "name": "Modulex Pastel Green",         "hex": "#7db538", trans: false },
//  { "id": 1031,  "name": "Modulex Olive Green",          "hex": "#7c9051", trans: false },
//  { "id": 1032,  "name": "Modulex Aqua Green",           "hex": "#27867e", trans: false },
//  { "id": 1033,  "name": "Modulex Teal Blue",            "hex": "#467083", trans: false },
//  { "id": 1034,  "name": "Modulex Tile Blue",            "hex": "#0057a6", trans: false },
//  { "id": 1035,  "name": "Modulex Medium Blue",          "hex": "#61afff", trans: false },
//  { "id": 1036,  "name": "Modulex Pastel Blue",          "hex": "#68aece", trans: false },
//  { "id": 1037,  "name": "Modulex Violet",               "hex": "#bd7d85", trans: false },
//  { "id": 1038,  "name": "Modulex Pink",                 "hex": "#f785b1", trans: false },
//  { "id": 1039,  "name": "Modulex Clear",                "hex": "#ffffff", trans: false },
//  { "id": 1040,  "name": "Modulex Foil Dark Gray",       "hex": "#595d60", trans: false },
//  { "id": 1041,  "name": "Modulex Foil Light Gray",      "hex": "#9c9c9c", trans: false },
//  { "id": 1042,  "name": "Modulex Foil Dark Green",      "hex": "#006400", trans: false },
//  { "id": 1043,  "name": "Modulex Foil Light Green",     "hex": "#7db538", trans: false },
//  { "id": 1044,  "name": "Modulex Foil Dark Blue",       "hex": "#0057a6", trans: false },
//  { "id": 1045,  "name": "Modulex Foil Light Blue",      "hex": "#68aece", trans: false },
//  { "id": 1046,  "name": "Modulex Foil Violet",          "hex": "#4b0082", trans: false },
//  { "id": 1047,  "name": "Modulex Foil Red",             "hex": "#8b0000", trans: false },
//  { "id": 1048,  "name": "Modulex Foil Yellow",          "hex": "#fed557", trans: false },
//  { "id": 1049,  "name": "Modulex Foil Orange",          "hex": "#f7ad63", trans: false },
    { "id": 1050,  "name": "Coral",                        "hex": "#ff698f", trans: false },
    { "id": 1051,  "name": "Pastel Blue",                  "hex": "#5ac4da", trans: false },
//  { "id": 1052,  "name": "Glitter Trans-Orange",         "hex": "#f08f1c", trans: true  },
//  { "id": 1053,  "name": "Opal Trans-Light Blue",        "hex": "#68bcc5", trans: true  },
//  { "id": 1054,  "name": "Opal Trans-Dark Pink",         "hex": "#ce1d9b", trans: true  },
//  { "id": 1055,  "name": "Opal Trans-Clear",             "hex": "#fcfcfc", trans: true  },
//  { "id": 1056,  "name": "Opal Trans-Brown",             "hex": "#583927", trans: true  },
//  { "id": 1057,  "name": "Trans-Light Bright Green",     "hex": "#c9e788", trans: true  },
//  { "id": 1058,  "name": "Trans-Light Green",            "hex": "#94e5ab", trans: true  },
//  { "id": 1059,  "name": "Opal Trans-Purple",            "hex": "#8320b7", trans: true  },
//  { "id": 1060,  "name": "Opal Trans-Bright Green",      "hex": "#84b68d", trans: true  },
//  { "id": 1061,  "name": "Opal Trans-Dark Blue",         "hex": "#0020a0", trans: true  },
    { "id": 1062,  "name": "Vibrant Yellow",               "hex": "#ebd800", trans: false },
//  { "id": 1063,  "name": "Pearl Copper",                 "hex": "#b46a00", trans: false },
//  { "id": 1064,  "name": "Fabuland Red",                 "hex": "#ff8014", trans: false },
    { "id": 1065,  "name": "Reddish Gold",                 "hex": "#ac8247", trans: false },
    { "id": 1066,  "name": "Curry",                        "hex": "#dd982e", trans: false },
    { "id": 1067,  "name": "Dark Nougat",                  "hex": "#ad6140", trans: false },
    { "id": 1068,  "name": "Bright Reddish Orange",        "hex": "#ee5434", trans: false },
//  { "id": 1069,  "name": "Pearl Red",                    "hex": "#d60026", trans: false },
//  { "id": 1070,  "name": "Pearl Blue",                   "hex": "#0059a3", trans: false },
//  { "id": 1071,  "name": "Pearl Green",                  "hex": "#008e3c", trans: false },
//  { "id": 1072,  "name": "Pearl Brown",                  "hex": "#57392c", trans: false },
//  { "id": 1073,  "name": "Pearl Black",                  "hex": "#0a1327", trans: false },
//  { "id": 1074,  "name": "Duplo Blue",                   "hex": "#009ece", trans: false },
//  { "id": 1075,  "name": "Duplo Medium Blue",            "hex": "#3e95b6", trans: false },
//  { "id": 1076,  "name": "Duplo Lime",                   "hex": "#fff230", trans: false },
//  { "id": 1077,  "name": "Fabuland Lime",                "hex": "#78fc78", trans: false },
//  { "id": 1078,  "name": "Duplo Medium Green",           "hex": "#468a5f", trans: false },
//  { "id": 1079,  "name": "Duplo Light Green",            "hex": "#60ba76", trans: false },
    { "id": 1080,  "name": "Light Tan",                    "hex": "#f3c988", trans: false },
    { "id": 1081,  "name": "Rust Orange",                  "hex": "#872b17", trans: false },
//  { "id": 1082,  "name": "Clikits Pink",                 "hex": "#fe78b0", trans: false },
//  { "id": 1083,  "name": "Two-tone Copper",              "hex": "#945148", trans: false },
//  { "id": 1084,  "name": "Two-tone Gold",                "hex": "#ab673a", trans: false },
//  { "id": 1085,  "name": "Two-tone Silver",              "hex": "#737271", trans: false },
//  { "id": 1086,  "name": "Pearl Lime",                   "hex": "#6a7944", trans: false },
//  { "id": 1087,  "name": "Duplo Pink",                   "hex": "#ff879c", trans: false },
    { "id": 1088,  "name": "Medium Brown",                 "hex": "#755945", trans: false },
    { "id": 1089,  "name": "Warm Tan",                     "hex": "#cca373", trans: false },
//  { "id": 1090,  "name": "Duplo Turquoise",              "hex": "#3fb69e", trans: false },
    { "id": 1091,  "name": "Warm Yellowish Orange",        "hex": "#ffcb78", trans: false },
//  { "id": 1092,  "name": "Metallic Copper",              "hex": "#764d3b", trans: false },
    { "id": 1093,  "name": "Light Lilac",                  "hex": "#9195ca", trans: false },
    { "id": 1094,  "name": "Trans-Medium Purple",          "hex": "#8d73b3", trans: false },
//  { "id": 1095,  "name": "Trans-Black",                  "hex": "#635f52", trans: true  },
//  { "id": 1096,  "name": "Glitter Trans-Bright Green",   "hex": "#d9e4a7", trans: true  },
//  { "id": 1097,  "name": "Glitter Trans-Medium Purple",  "hex": "#8d73b3", trans: true  },
//  { "id": 1098,  "name": "Glitter Trans-Green",          "hex": "#84b68d", trans: true  },
//  { "id": 1099,  "name": "Glitter Trans-Pink",           "hex": "#e4adc8", trans: true  },
//  { "id": 1100,  "name": "Clikits Yellow",               "hex": "#ffcf0b", trans: false },
//  { "id": 1101,  "name": "Duplo Dark Purple",            "hex": "#5f27aa", trans: false },
//  { "id": 1102,  "name": "Trans-Neon Red",               "hex": "#ff0040", trans: true  },
//  { "id": 1103,  "name": "Pearl Titanium",               "hex": "#3e3c39", trans: false },
//  { "id": 1104,  "name": "HO Aqua",                      "hex": "#b3d7d1", trans: false },
//  { "id": 1105,  "name": "HO Azure",                     "hex": "#1591cb", trans: false },
//  { "id": 1106,  "name": "HO Blue-gray",                 "hex": "#354e5a", trans: false },
//  { "id": 1107,  "name": "HO Cyan",                      "hex": "#5b98b3", trans: false },
//  { "id": 1108,  "name": "HO Dark Aqua",                 "hex": "#a7dccf", trans: false },
//  { "id": 1109,  "name": "HO Dark Blue",                 "hex": "#0a3463", trans: false },
//  { "id": 1110,  "name": "HO Dark Gray",                 "hex": "#6d6e5c", trans: false },
//  { "id": 1111,  "name": "HO Dark Green",                "hex": "#184632", trans: false },
//  { "id": 1112,  "name": "HO Dark Lime",                 "hex": "#b2b955", trans: false },
//  { "id": 1113,  "name": "HO Dark Red",                  "hex": "#631314", trans: false },
//  { "id": 1114,  "name": "HO Dark Sand Green",           "hex": "#627a62", trans: false },
//  { "id": 1115,  "name": "HO Dark Turquoise",            "hex": "#10929d", trans: false },
//  { "id": 1116,  "name": "HO Earth Orange",              "hex": "#bb771b", trans: false },
//  { "id": 1117,  "name": "HO Gold",                      "hex": "#b4a774", trans: false },
//  { "id": 1118,  "name": "HO Light Aqua",                "hex": "#a3d1c0", trans: false },
//  { "id": 1119,  "name": "HO Light Brown",               "hex": "#965336", trans: false },
//  { "id": 1120,  "name": "HO Light Gold",                "hex": "#cdc298", trans: false },
//  { "id": 1121,  "name": "HO Light Tan",                 "hex": "#f9f1c7", trans: false },
//  { "id": 1122,  "name": "HO Light Yellow",              "hex": "#f5fab7", trans: false },
//  { "id": 1123,  "name": "HO Medium Blue",               "hex": "#7396c8", trans: false },
//  { "id": 1124,  "name": "HO Medium Red",                "hex": "#c01111", trans: false },
//  { "id": 1125,  "name": "HO Metallic Blue",             "hex": "#0d4763", trans: false },
//  { "id": 1126,  "name": "HO Metallic Dark Gray",        "hex": "#5e5e5e", trans: false },
//  { "id": 1127,  "name": "HO Metallic Green",            "hex": "#879867", trans: false },
//  { "id": 1128,  "name": "HO Metallic Sand Blue",        "hex": "#5f7d8c", trans: false },
//  { "id": 1129,  "name": "HO Olive Green",               "hex": "#9b9a5a", trans: false },
//  { "id": 1130,  "name": "HO Rose",                      "hex": "#d06262", trans: false },
//  { "id": 1131,  "name": "HO Sand Blue",                 "hex": "#6e8aa6", trans: false },
//  { "id": 1132,  "name": "HO Sand Green",                "hex": "#a0bcac", trans: false },
//  { "id": 1133,  "name": "HO Tan",                       "hex": "#e4cd9e", trans: false },
//  { "id": 1134,  "name": "HO Titanium",                  "hex": "#616161", trans: false },
    { "id": 1135,  "name": "Metal",                        "hex": "#a5adb4", trans: false },
    { "id": 1136,  "name": "Reddish Orange",               "hex": "#ca4c0b", trans: false },
    { "id": 1137,  "name": "Sienna Brown",                 "hex": "#915c3c", trans: false },
    { "id": 1138,  "name": "Umber Brown",                  "hex": "#5e3f33", trans: false },
//  { "id": 1139,  "name": "Opal Trans-Yellow",            "hex": "#f5cd2f", trans: true  },


    //Ali Express colors, HEX-color determined via photo:
    { "id": 99010,  "name": "A01 Black",              "hex": "#05131d", trans: false, order: 10, }, // 06
    { "id": 99020,  "name": "A02 Blue",               "hex": "#0b408b", trans: false, order: 20, }, //
    { "id": 99030,  "name": "A03 Bright Light Blue",  "hex": "#2173a5", trans: false, order: 30, }, // 40
    { "id": 99040,  "name": "A04 Salmon",             "hex": "#fb7156", trans: false, order: 40, }, //
    { "id": 99050,  "name": "A05 Dark Blue",          "hex": "#27314d", trans: false, order: 50, }, // 42
    { "id": 99060,  "name": "A06 Dark Bluish Gray",   "hex": "#706c68", trans: false, order: 60, }, // 04
    { "id": 99070,  "name": "A07 Dark Brown",         "hex": "#301c14", trans: false, order: 70, }, // 18
    { "id": 99080,  "name": "A08 Dark Pink",          "hex": "#ce5373", trans: false, order: 80, }, // 28
    { "id": 99090,  "name": "A09 Dark Red",           "hex": "#731f1c", trans: false, order: 90, }, //
    { "id": 99100,  "name": "A10 Dark Tan",           "hex": "#957a49", trans: false, order: 100, }, // 20
    { "id": 99110,  "name": "A11 Flat Silver",        "hex": "#a4a9b1", trans: false, order: 110, }, //
    { "id": 99120,  "name": "A12 Light Bluish Gray",  "hex": "#a9a6a7", trans: false, order: 120, }, // 03
//  { "id": 99131,  "name": "A13 Light Flesh (13A)",  "hex": "#d6a268", trans: false, order: 131, }, // 11
//  { "id": 99132,  "name": "A26 Flesh Red (13B)",    "hex": "#d59d65", trans: false, order: 132, }, // 13
//  { "id": 99131,  "name": "A13 Light Flesh (13A)",  "hex": "#feccb0", trans: false, order: 131, }, // 11
//  { "id": 99132,  "name": "A26 Flesh Red (13B)",    "hex": "#f6d7b3", trans: false, order: 132, }, // 13
    { "id": 99131,  "name": "A13 Light Flesh (13A)",  "hex": "#feccb0", trans: false, order: 130, }, // 11
    { "id": 99132,  "name": "A26 Flesh Red (13B)",    "hex": "#fda98f", trans: false, order: 260, }, // 13
    { "id": 99140,  "name": "A14 Lime",               "hex": "#829102", trans: false, order: 140, }, //
    { "id": 99150,  "name": "A15 Magenta",            "hex": "#af2854", trans: false, order: 150, }, // 29
    { "id": 99160,  "name": "A16 Medium Azure 1000",  "hex": "#6d98c4", trans: false, order: 160, }, // 37 Medium Azure 1000-pcs pack
    { "id": 99170,  "name": "A17 Medium Blue",        "hex": "#9dbbd5", trans: false, order: 170, }, // 36
    { "id": 99180,  "name": "A18 Nougat",             "hex": "#bf702a", trans: false, order: 180, }, //
    { "id": 99190,  "name": "A19 Olive Green",        "hex": "#70632a", trans: false, order: 190, }, // 46
    { "id": 99200,  "name": "A20 Reddish Brown",      "hex": "#59321e", trans: false, order: 200, }, //
    { "id": 99210,  "name": "A21 Sand Blue",          "hex": "#6c7785", trans: false, order: 210, }, // 43
    { "id": 99220,  "name": "A22 Tan",                "hex": "#d0b57b", trans: false, order: 220, }, // 19
    { "id": 99230,  "name": "A23 White",              "hex": "#f6f1e9", trans: false, order: 230, }, // 01
    { "id": 99240,  "name": "A24 Yellowish Green",    "hex": "#cbcd69", trans: false, order: 240, }, //
    { "id": 99250,  "name": "A25 Medium Azure 300",   "hex": "#44a0c4", trans: false, order: 250, }, // Medium Azure 300-pcs pack

];

const HEX_TO_COLOR_NAME = {};
const COLOR_NAME_TO_HEX = {};
ALL_BRICKLINK_SOLID_COLORS.forEach((color) => {
    HEX_TO_COLOR_NAME[color.hex] = color.name;
    COLOR_NAME_TO_HEX[color.name] = color.hex;
});

const COLOR_NAME_TO_ID = {};
ALL_BRICKLINK_SOLID_COLORS.forEach((color) => {
    COLOR_NAME_TO_ID[color.name] = color.id;
});

const KNOWN_BRICKLINK_STUD_COLOR_NAMES = [
    "Black",
    "Blue",
    "Bright Green",
    "Bright Light Yellow",
    "Bright Pink",
    "Brown",
    "Dark Blue",
    "Dark Bluish Gray",
    "Dark Brown",
    "Dark Gray",
    "Dark Orange",
    "Dark Pink",
    "Dark Purple",
    "Dark Red",
    "Dark Tan",
    "Green",
    "Light Bluish Gray",
    "Light Gray",
    "Lime",
    "Magenta",
    "Medium Azure",
    "Medium Lime",
    "Medium Nougat",
    "Olive Green",
    "Orange",
    "Red",
    "Reddish Brown",
    "Sand Blue",
    "Sand Green",
    "Tan",
    "White",
    "Yellow",
    "Yellowish Green",
    "Trans-Black",
    "Trans-Bright Green",
    "Trans-Clear",
    "Trans-Dark Blue",
    "Trans-Dark Pink",
    "Trans-Green",
    "Trans-Light Blue",
    "Trans-Medium Blue",
    "Trans-Neon Green",
    "Trans-Neon Orange",
    "Trans-Neon Yellow",
    "Trans-Orange",
    "Trans-Purple",
    "Trans-Red",
    "Trans-Yellow",
    "Chrome Antique Brass",
    "Chrome Gold",
    "Chrome Silver",
    "Flat Silver",
    "Pearl Dark Gray",
    "Pearl Gold",
    "Pearl Light Gray",
    "Metallic Silver",
    "Glow In Dark Opaque",
    "Glow In Dark White",
    "Medium Lavender", // manually added from Batman
    "Light Aqua", // manually added from Batman
];

const KNOWN_BRICKLINK_TILE_COLOR_NAMES = [
//     // Taken from https://www.bricklink.com/v2/catalog/catalogitem.page?P=98138#T=C
//     "Black",
//     "Blue",
//     "Bright Green",
//     "Bright Light Blue",
//     "Bright Light Orange",
//     "Bright Light Yellow",
//     "Bright Pink",
//     "Coral",
//     "Dark Azure",
//     "Dark Blue",
//     "Dark Bluish Gray",
//     "Dark Brown",
//     "Dark Green",
//     "Dark Orange",
//     "Dark Pink",
//     "Dark Purple",
//     "Dark Red",
//     "Dark Tan",
//     "Dark Turquoise",
//     "Green",
//     "Lavender",
//     "Light Aqua",
//     "Light Bluish Gray",
//     "Light Nougat A",
//     "Light Nougat B",
//     "Lime",
//     "Magenta",
//     "Medium Azure",
//     "Medium Blue",
//     "Medium Lavender",
//     "Medium Nougat",
//     "Neon Yellow",
//     "Nougat",
//     "Olive Green",
//     "Orange",
//     "Red",
//     "Reddish Brown",
//     "Sand Blue",
//     "Tan",
//     "White",
//     "Yellow",
//     "Yellowish Green",
// //  "Trans-Black",
// //  "Trans-Bright Green",
// //  "Trans-Brown",
// //  "Trans-Clear",
// //  "Trans-Dark Blue",
// //  "Trans-Dark Pink",
// //  "Trans-Green",
// //  "Trans-Light Blue",
// //  "Trans-Orange",
// //  "Trans-Purple",
// //  "Trans-Red",
// //  "Trans-Yellow",
//     "Flat Silver",
// //  "Pearl Gold",
// //  "Satin Trans-Bright Green",
// //  "Satin Trans-Clear",
// //  "Satin Trans-Dark Blue",
// //  "Satin Trans-Light Blue",
// //  "Glow In Dark White",
// //  "Glitter Trans-Clear",
// //  "Glitter Trans-Dark Pink",
// //  "Glitter Trans-Light Blue",


    // Purchased colors:
    "A01 Black",
    "A02 Blue",
    "A03 Bright Light Blue",
    "A04 Salmon",
    "A05 Dark Blue",
    "A06 Dark Bluish Gray",
    "A07 Dark Brown",
    "A08 Dark Pink",
    "A09 Dark Red",
    "A10 Dark Tan",
    "A11 Flat Silver",
    "A12 Light Bluish Gray",
    "A13 Light Flesh (13A)",
    "A26 Flesh Red (13B)",
    "A14 Lime",
    "A15 Magenta",
    "A16 Medium Azure 1000",
    "A17 Medium Blue",
    "A18 Nougat",
    "A19 Olive Green",
    "A20 Reddish Brown",
    "A21 Sand Blue",
    "A22 Tan",
    "A23 White",
    "A24 Yellowish Green",
    "A25 Medium Azure 300",
];

const BRICKLINK_STUD_COLORS = ALL_BRICKLINK_SOLID_COLORS.filter((color) =>
    KNOWN_BRICKLINK_STUD_COLOR_NAMES.includes(color.name)
).sort((a, b) => {
    return a.name > b.name ? 1 : -1;
});

const BRICKLINK_TILE_COLORS = ALL_BRICKLINK_SOLID_COLORS.filter((color) =>
    KNOWN_BRICKLINK_TILE_COLOR_NAMES.includes(color.name)
).sort((a, b) => {
    return a.name > b.name ? 1 : -1;
});

const ADDITIONAL_COLORS = ["Very Light Gray"];
let ALL_VALID_BRICKLINK_COLORS = ALL_BRICKLINK_SOLID_COLORS.sort((a, b) => {
    return a.name > b.name ? 1 : -1;
});
// .filter(
//     color =>
//         KNOWN_BRICKLINK_STUD_COLOR_NAMES.includes(color.name) ||
//         KNOWN_BRICKLINK_TILE_COLOR_NAMES.includes(color.name) ||
//         ADDITIONAL_COLORS.includes(color.name)
// ).sort((a, b) => {
//     return a.name > b.name ? 1 : -1;
// });

const PIXEL_TYPE_OPTIONS = [
    {
        name: "1x1 Round Tile",
        number: 98138,
    },
    {
        name: "1x1 Round Plate",
        number: 4073,
    },
    {
        name: "1x1 Square Tile",
        number: "3070b",
    },
    {
        name: "1x1 Square Plate",
        number: 3024,
    },
    {
        name: "1x1 Square Brick",
        number: 3005,
    },
    {
        name: "Variable Tile",
        number: "variable_tile",
    },
    {
        name: "Variable Plate",
        number: "variable_plate",
    },
    {
        name: "Variable Brick",
        number: "variable_brick",
    },
];

// use this for instructions - we prioritize readability over accuracy here
const PIXEL_TYPE_TO_FLATTENED = {
    98138: 98138,
    4073: 98138,
    3024: "3070b",
    "3070b": "3070b",
    3005: "3070b",
    variable_tile: "variable_tile",
    variable_plate: "variable_tile",
    variable_brick: "variable_tile",
};
